[workspace]
resolver = "2"
members = [
    "silentpayments",
    "example-crates/example_silentpayments", "dleq",
]

[workspace.package]
authors = ["Bitcoin Dev Kit Developers"]

[workspace.lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
