name: Code Coverage

on:
  push:
    branches: [ "develop" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
            toolchain: nightly
            components: llvm-tools-preview
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.8
      - name: Install cargo-llvm-cov
        run: if [[ ! -e ~/.cargo/bin/cargo-llvm-cov ]]; then cargo install cargo-llvm-cov; fi
      - name: Test and report coverage
        run: cargo +nightly llvm-cov -q --doctests --branch --workspace --ignore-filename-regex "example-crates/*"
